# Http Server
server:
  port: 8025
  compression:
    enabled: true
  servlet:
    encoding:
       charset: UTF-8
       enabled: true

# Spring Settings
spring:
  application:
    name: api-gateway
  profiles:
    active: default
  mandatory-file-encoding: UTF-8
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: authorization-service
        uri: lb://authorization-service
        predicates:
        - Path=/authorization/**
        filters:
        - RewritePath=/authorization/(?<path>.*), /$\{path}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
    register-with-eureka: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
    
api-docs.endpoints:
  authorization-service:
    gateway-prefix: /api
    service-url: lb://authorization-service
    service-path: /resource/api-docs
