# Http Server
server:
  port: 8025
  compression:
    enabled: true
  servlet:
    encoding:
       charset: UTF-8
       enabled: true

# Spring Settings
spring:
  application:
    name: authorization-service
  profiles:
    active: default
  mandatory-file-encoding: UTF-8
  #main:
  #  web-application-type: reactive
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
